version: '3.8'

services:
  # Service untuk Back-end (Python)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  # Service untuk Front-end (HTML/JS/CSS statis)
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend